.PHONY: run migrate seed create-user build test

run:
	go run ./cmd/api

migrate:
	go run ./cmd/migrate

seed:
	go run ./cmd/seed

create-user:
	go run ./cmd/create-user

build:
	go build ./cmd/api

test:
	go test ./...
